dataset_params:
  root_dir: 'data/'
  frame_shape: [256, 256, 3]
  is_full: True
  sample_n_frames: 16

model_params:
  size: 256
  latent_dim_style: 512
  latent_dim_motion: 20
  channel_multiplier: 1

animate_params:
  num_pairs: 100