# data:
#   root_dir: 'data/'
#   sample_size:  [512, 512]
#   is_full: True
#   sample_n_frames: 16
#   pairs_list: 'final_pairs.csv'

data:
  root_dir: '/home/junho/jieun/datasets/vox1_png/'
  sample_size:  [512, 512]
  is_full: false
  sample_n_frames: 16
  pairs_list: 'final_pairs.csv'


noise_scheduler_kwargs:
  beta_start: 0.00085
  beta_end: 0.012
  beta_schedule: "linear"
  clip_sample: false
  steps_offset: 1
  ### Zero-SNR params
  prediction_type: "v_prediction"
  rescale_betas_zero_snr: True
  timestep_spacing: "trailing"

animate_params:
  num_pairs: 100
  
pretrained_base_model_path: './pretrained_model/stable-diffusion-v1-5'
pretrained_vae_path: './pretrained_model/sd-vae-ft-mse'
image_encoder_path: './pretrained_model/image_encoder'
motion_adapter_path: './pretrained_model/animatediff'

denoising_unet_path: "./checkpoint/denoising_unet_stage2_v2.pth"
reference_unet_path: "./checkpoint/appearance_unet_stage1.pth"
lia_model_path: "./checkpoint/lia_stage1.pth"

weight_dtype: 'fp16'
pipeline_mode: 'vid2vid'