data:
  root_dir: 'data/'
  sample_size:  [512, 512]
  is_full: True
  sample_stride: 1
  sample_n_frames: 16

noise_scheduler_kwargs:
  beta_start: 0.00085
  beta_end: 0.012
  beta_schedule: "linear"
  clip_sample: false
  steps_offset: 1
  ### Zero-SNR params
  prediction_type: "v_prediction"
  rescale_betas_zero_snr: True
  timestep_spacing: "trailing"

animate_params:
  num_pairs: 100
  
pretrained_base_model_path: './pretrained_model/stable-diffusion-v1-5'
pretrained_vae_path: './pretrained_model/sd-vae-ft-mse'
image_encoder_path: './pretrained_model/image_encoder'

denoising_unet_path: "./checkpoint/denoising_unet.pth"
reference_unet_path: "./checkpoint/appearance_unet.pth"
lia_model_path: "./checkpoint/lia.pth"

weight_dtype: 'fp16'
pipeline_mode: 'img2img'