checkpoint: 'checkpoint/model_state-415001.th' 

dataset_params:
  root_dir: '/home/junho/jieun/datasets/vox1_png'
  frame_shape: [256, 256, 3]
  is_full: false
  sample_n_frames: 16
  pairs_list: 'final_pairs.csv'

animate_params:
  num_pairs: 100

model:
  model_config: "models/x_portrait/model/config/cldm_v15_appearance_pose_local_mm.yaml"
  reinit_hint_block: false
  sd_locked: true
  only_mid_control: false
  control_type: "appearance_pose_local_mm"
  control_mode: "controlnet_important"
  wonoise: true

training:
  local_rank: 0
  world_size: 1
  use_fp16: true
  compile: false
  eta: 0.0
  ema_rate: 0.0